### PR TITLE
Google prompt parameter

### PR DESCRIPTION
**Pull request by 3da**
Hello.

I need parameter Prompt in Google OAauth2.

Thanks.

### CODE REVIEW

**Comment by jchannon** [comment]
This is a fork from Microsoft's Katana project for reference use only. Sorry

**Comment by 3da** [comment]
Can you please leave the link to real repository for other guys?

**Comment by jchannon** [comment]
https://github.com/aspnet/AspNetKatana/

**Comment by 3da** [comment]
I mean leave the link in the project's description

**Comment by jchannon** [comment]
Done

**Pull request closed without merging**
